import assert from "node:assert/strict";
import test from "node:test";
import { compareDebtExtraPayment, projectDebtPayoff, projectDebtStrategy } from "./debt-payoff.ts";

test("projects payoff for a single amortizing debt", () => { const result = projectDebtPayoff({ balance: 10000, annualInterestRate: 12, minimumPayment: 300 }); assert.equal(result.payoffPossible, true); assert.ok(result.months !== null && result.months > 35 && result.months < 45); });
test("extra payments reduce time and interest", () => { const result = compareDebtExtraPayment({ balance: 10000, annualInterestRate: 12, minimumPayment: 300, extraMonthlyPayment: 200 }); assert.ok(result.monthsSaved !== null && result.monthsSaved > 10); assert.ok(result.interestSaved !== null && result.interestSaved > 700); });
test("reports non-amortizing single debt as impossible", () => { assert.equal(projectDebtPayoff({ balance: 10000, annualInterestRate: 24, minimumPayment: 100 }).payoffPossible, false); });
test("avalanche targets highest rate first", () => { const debts = [{ id: "a", name: "Card A", balance: 5000, annualInterestRate: 24, minimumPayment: 150 }, { id: "b", name: "Loan B", balance: 2000, annualInterestRate: 8, minimumPayment: 100 }]; assert.equal(projectDebtStrategy(debts, 300, "avalanche").payoffOrder[0], "Card A"); });
test("snowball targets smallest balance first", () => { const debts = [{ id: "a", name: "Card A", balance: 5000, annualInterestRate: 24, minimumPayment: 150 }, { id: "b", name: "Loan B", balance: 2000, annualInterestRate: 8, minimumPayment: 100 }]; assert.equal(projectDebtStrategy(debts, 300, "snowball").payoffOrder[0], "Loan B"); });
test("avalanche is not more expensive than snowball for the same debts", () => { const debts = [{ id: "a", name: "Card A", balance: 6000, annualInterestRate: 22, minimumPayment: 180 }, { id: "b", name: "Loan B", balance: 2500, annualInterestRate: 7, minimumPayment: 90 }, { id: "c", name: "Card C", balance: 3500, annualInterestRate: 16, minimumPayment: 120 }]; const avalanche = projectDebtStrategy(debts, 400, "avalanche"); const snowball = projectDebtStrategy(debts, 400, "snowball"); assert.ok((avalanche.totalInterest ?? Infinity) <= (snowball.totalInterest ?? Infinity)); });
test("extra strategy budget can rescue a debt whose minimum does not cover interest", () => { const debts = [{ id: "a", name: "High APR", balance: 10000, annualInterestRate: 24, minimumPayment: 100 }]; const result = projectDebtStrategy(debts, 300, "avalanche"); assert.equal(result.payoffPossible, true); });
test("duplicate debt names are both recorded in payoff order", () => { const debts = [{ id: "a", name: "Card", balance: 1000, annualInterestRate: 10, minimumPayment: 100 }, { id: "b", name: "Card", balance: 2000, annualInterestRate: 8, minimumPayment: 100 }]; const result = projectDebtStrategy(debts, 200, "snowball"); assert.equal(result.payoffOrder.length, 2); });
test("zero household debt budget is impossible when balances remain", () => { const result = projectDebtStrategy([{ id: "a", name: "Loan", balance: 1000, annualInterestRate: 0, minimumPayment: 0 }], 0, "snowball"); assert.equal(result.payoffPossible, false); });
